name: ecommerce
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

#---------------------packages----------------------------#
dependencies:
  flutter:
    sdk: flutter


#utility packages

#icons

  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  

#state management
  get: ^4.6.6
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.6
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  firebase_core: ^2.31.0
  lottie: ^3.1.2
  connectivity_plus: ^5.0.1
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.4
  google_sign_in: ^6.2.1
  shimmer: ^3.0.0
  image_picker: ^1.1.1
  firebase_storage: ^11.7.6
  cached_network_image: ^3.3.1
  rating_dialog: ^2.0.4
  shared_preferences: ^2.2.3
  universal_io: ^2.2.2
  image_picker_web: ^4.0.0
  flutter_colorpicker: ^1.1.0
  color: ^3.0.0
  path_provider: ^2.1.3
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.2.1+2
  myfatoorah_flutter: ^3.0.14
  my_fatoorah: ^3.3.0
  uuid: ^3.0.7
  # file_picker: ^8.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

#--------------------- Local Assets ----------------------------#
  assets:
     - assets/images/
     - assets/icons/
     - assets/icons/adidas.jpg
     #- assets/fonts/
     - assets/logos/
     - assets/animations/
     - assets/images/on_boarding_images/
     - assets/images/email_images/
     - assets/images/banners/
     - assets/icons/categories/
  fonts:
    - family: Popins
      fonts:
        - asset: assets\fonts\Poppins-Thin.ttf
        - asset: assets\fonts\Poppins-Regular.ttf
        - asset: assets\fonts\Poppins-ExtraBold.ttf
        - asset: assets\fonts\Poppins-Bold.ttf
        - asset: assets\fonts\Poppins-BoldItalic.ttf
    

