name: ecommerce
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

#---------------------packages----------------------------#
dependencies:
  flutter:
    sdk: flutter


#utility packages

#icons

  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  

#state management
  get: ^4.6.6
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.6
  get_storage: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

#--------------------- Local Assets ----------------------------#
  assets:
     - assets/images/
     - assets/icons/
     #- assets/fonts/
     - assets/logos/
  fonts:
    - family: Popins
      fonts:
        - asset: assets\fonts\Poppins-Thin.ttf
        - asset: assets\fonts\Poppins-Regular.ttf
        - asset: assets\fonts\Poppins-ExtraBold.ttf
        - asset: assets\fonts\Poppins-Bold.ttf
        - asset: assets\fonts\Poppins-BoldItalic.ttf
    

